<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"农庄管理",
                        "menuJump":"列表",
                        "tableName":"nongzhuang"
                    }
                ],
                "menu":"农庄管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"特色菜管理",
                        "menuJump":"列表",
                        "tableName":"tesecai"
                    }
                ],
                "menu":"特色菜管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"游玩项目管理",
                        "menuJump":"列表",
                        "tableName":"youwanxiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"游玩项目留言管理",
                        "menuJump":"列表",
                        "tableName":"youwanxiangmuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"游玩项目订单管理",
                        "menuJump":"列表",
                        "tableName":"youwanxiangmuOrder"
                    }
                ],
                "menu":"游玩项目管理"
            }
            ,{
                "child":[
                    {
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"住房管理",
						"menuJump":"列表",
						"tableName":"zhufang"
					}
					,
					{
						"buttons":[
							"查看",
							"修改",
							"删除"
						],
						"menu":"住房留言管理",
						"menuJump":"列表",
						"tableName":"zhufangLiuyan"
					}
					,
					{
						"buttons":[
							"查看",
							"删除"
						],
						"menu":"住房订单管理",
						"menuJump":"列表",
						"tableName":"zhufangOrder"
					}
                ],
                "menu":"住房管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"菜品口味管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKouwei"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"住房类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZhufang"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	       {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"农庄管理",
	                    "menuJump":"列表",
	                    "tableName":"nongzhuang"
	                }
	            ],
	            "menu":"农庄管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"特色菜管理",
	                    "menuJump":"列表",
	                    "tableName":"tesecai"
	                }
	            ],
	            "menu":"特色菜管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"游玩项目管理",
	                    "menuJump":"列表",
	                    "tableName":"youwanxiangmu"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"游玩项目留言管理",
	                    "menuJump":"列表",
	                    "tableName":"youwanxiangmuLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"游玩项目订单管理",
	                    "menuJump":"列表",
	                    "tableName":"youwanxiangmuOrder"
	                }
	            ],
	            "menu":"游玩项目管理"
	        }
	        ,{
	            "child":[
	                {
						"buttons":[
							"查看"
						],
						"menu":"住房管理",
						"menuJump":"列表",
						"tableName":"zhufang"
					}
					,
					{
						"buttons":[
							"查看"
						],
						"menu":"住房留言管理",
						"menuJump":"列表",
						"tableName":"zhufangLiuyan"
					}
					,
					{
						"buttons":[
							"查看"
						],
						"menu":"住房订单管理",
						"menuJump":"列表",
						"tableName":"zhufangOrder"
					}
	            ],
	            "menu":"住房管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
